### ISSUE TITLE
Remove items from tables

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/jQuery-json-editor#10]
Like #5 but for removing items. :sparkle:

**Comment by IonicaBizau** [comment]
This includes objects and non-objects (strings, numbers etc).

**Comment by IonicaBizau** [comment]
@silviubogan In the future, only assign me the PRs, not the issues you worked on.

**Comment by silviubogan** [comment]
@IonicaBizau, OK, thanks for the advice! :smiley: :+1:
