### ISSUE TITLE
We should refactor the array schema

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/jQuery-json-editor#12]
Right now it doesn't allow us any kind of options, since it's an array:

``` js
someArray: [
   {
        ...
   }
]
```

Currently the best idea I have is to have something like:

``` js
someArray: {
    type: "array",
    item: {
       /* item schema */
    }
}
```

@silviubogan Any better ideas?

**Comment by silviubogan** [comment]
In [the `example/index.html` file](https://cdn.rawgit.com/jillix/jQuery-json-editor/48b9221e200092900196e9dc05f36300970a6c8b/example/index.html) I see that the `hobbies` array schema looks like this:
```js
hobbies: { label: "Hobbies",
    schema: {
        possible: [
            "piano",
            "blogging",
            "computers",
            "science",
            "music"
        ]
    }
}
```

The `type` property of the schema is in this example inferred from the data, so the final schema looks like this:

```js
hobbies: { label: "Hobbies",
    type: "array",
    schema: {
        ...
    }
}
```

So, personally, I do not see any problem. :smiley:
