### ISSUE TITLE
Possible values

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/jQuery-json-editor#2]
```js
{
   schema: {
     age: {
         possible: [1, 2, 3, 4],
         type: "number" // "string", "date" etc
     } 
  }
}
```

**Comment by IonicaBizau** [comment]
This should create a `<select>` element containing `<option>`s. Depending on the type, they should have the correct type in the end (or maybe we don't need the type at all in this case since we have the possible values?).

**Comment by silviubogan** [comment]
A note related to my implementation: when the type is not specified, it is inferred from the data. :smiley:
