### ISSUE TITLE
Example or Demo of implementation

### ISSUE THREAD

**Issue by paultannenbaum** [jillix/jQuery-json-editor#46]
Looks like a very cool project! 

I think having an example of how the plugin is implemented in `README.md` or a static hosted demo where someone can view the source would go a really long way. Even after reading the docs I am unsure how to use the plugin, and I am not a js newb. I would be happy to open up a PR if you guys provide some guidance on how the plugin is implemented.

**Comment by IonicaBizau** [comment]
Hey @paultannenbaum! :sparkle: 

This project is heavily under development. @silviubogan takes care of it.
In the [`example`](https://github.com/jillix/jQuery-json-editor/tree/master/example) directory you can find the example.

[Here is the input data](https://github.com/jillix/jQuery-json-editor/blob/0ea104cf277da504bafe0b7d3b16a80b9f412162/example/index.html#L20-L133), [here is the initalization](https://github.com/jillix/jQuery-json-editor/blob/0ea104cf277da504bafe0b7d3b16a80b9f412162/example/js/handlers.js#L4-L6) and [here how  to get the data](https://github.com/jillix/jQuery-json-editor/blob/0ea104cf277da504bafe0b7d3b16a80b9f412162/example/js/handlers.js#L9).

[Here](https://cdn.rawgit.com/jillix/jQuery-json-editor/master/example/index.html) is a live demo provided by rawgit.com.

Contributions are more than welcome! :sparkles: Just make sure you discuss the changes in issues, so we can guide you to make them correctly. :balloon:

**Comment by paultannenbaum** [comment]
Awesome, thanks @IonicaBizau! Would you guys like me to add something to the Readme, or are you guys waiting for the project to become more stable before adding an example?

**Comment by IonicaBizau** [comment]
@paultannenbaum That would be amazing. @silviubogan is taking care of the code, but the docs are not *yet* updated. So, basically, fell free to improve them! :memo: :books:

**Comment by IonicaBizau** [comment]
@paultannenbaum I'm closing this. Like I mentioned, feel free to improve the docs since they are outdated most probably. :books:
